### ISSUE TITLE
could you confirm

### ISSUE THREAD

**Issue by surfzoid** [dw2102/HikVision-Data-Recovery#1]
hi, 
my NVR is a DS-7608NXI-I2 / S
this one seem to have an different file management.
it have binary and SQLLite files.
for the binary , i see HIKDISK00.bin and INDEX00.bin.
HIKDISK00.bin have the signature but at pos 16, after that i see assci-data "INDEX00.bin".
in INDEX00.bin file i see "000016   48 49 4B 42 54 52 45 45 00 00 00 00 00 00 00 00 48 49 4B 2E 32 30 31   HIKBTREE"
but if you read my comments here : 
https://github.com/bkbilly/libHikvision/issues/3
you will see in the list files there is few mp4 as sql lite with inside segment number, time and length of videos.
you also have an zip of my NVR files.
i thank you to took time to read me.

**Comment by dw2102** [comment]
Hi there, sorry for the late response, I was kind of busy.

It seem we got a misunderstanding about how we carve the video data. Can you explain to me from where you got those .bin and .sql files? Are you accessing the NVR somehow?

My script runs on a .dd or .001 file of the whole hard drive of the NVR. 

Edit: I changed the readme to clarify that my script only works with a image of the whole hard drive, like .dd or .001

**Comment by surfzoid** [comment]
Hi
I understand now, the bin and SQL files are  the files write by the NVR, in my case, an NFS share, we also see that with camera storage definition

**Comment by dw2102** [comment]
Hey, alright! I still think it is possible to extract the videos from your recorders' hard drive with my script. I've seen many HikVision NVR, most of them worked with this script.

I'm closing this issue now. Goodbye
